In [189]:
import numpy as np
import pandas as pd

In [190]:
df = pd.read_csv('../Desktop/vendorChoose.csv',encoding = 'big5') 
print(df) 
pd.DataFrame(df)

  Unnamed: 0  品質  交期   價格   服務
0   Vendor A  90  10  100  100
1   Vendor B  90  10  100  100
2   Vendor C  80  30  200   80
3   Vendor D  70  30  200   80
4   Vendor E  60  40  200   80
5   Vendor F  60  40  200   80


Unnamed: 0  品質  交期   價格   服務
0   Vendor A  90  10  100  100
1   Vendor B  90  10  100  100
2   Vendor C  80  30  200   80
3   Vendor D  70  30  200   80
4   Vendor E  60  40  200   80
5   Vendor F  60  40  200   80

In [254]:
# Create an empty list 
Row_list =[] 
Name_list = []
my_list = []

count_col = df.shape[1]

# Iterate over each row 
for index, rows in df.iterrows(): 
    # Create list for the current row 
    
    if 
    my_list =[rows[1], rows[2], rows[3], rows[4]]
    #for j in index<count_col:
        #my_list.append(rows[index])
    
    # append the list to the final list 
    Row_list.append(my_list)
    Name_list.append(rows[0])
    
print(Row_list)

0
['Vendor F']
1
['Vendor F', 60]
2
['Vendor F', 60, 40]
3
['Vendor F', 60, 40, 200]
4
['Vendor F', 60, 40, 200, 80]
[['Vendor F', 60, 40, 200, 80], ['Vendor F', 60, 40, 200, 80], ['Vendor F', 60, 40, 200, 80], ['Vendor F', 60, 40, 200, 80], ['Vendor F', 60, 40, 200, 80], ['Vendor F', 60, 40, 200, 80]]


In [192]:
C = None
optimum_choice = None


In [193]:
a= Row_list
w=[1,1,1,1]
I=[1,0,0,1]

In [194]:
# Decision Matrix
a = np.array(a, dtype=np.float).T
print(a)
#assert len(a.shape) == 2, "Decision matrix a must be 2D"

[[ 90.  90.  80.  70.  60.  60.]
 [ 10.  10.  30.  30.  40.  40.]
 [100. 100. 200. 200. 200. 200.]
 [100. 100.  80.  80.  80.  80.]]


In [195]:
# Number of alternatives, aspects
(n, J) = a.shape
print((n,J))
print(a.size)
print(n)

(4, 6)
24
4


In [196]:
 # Weight matrix
w = np.array(w, dtype=np.float)
print(w.size)
assert len(w.shape) == 1, "Weights array must be 1D"
assert w.size == n, "Weights array wrong length, " + "should be of length {}".format(n)


4


In [197]:
# Normalise weights to 1
w = w/sum(w)
print(w)

[0.25 0.25 0.25 0.25]


In [198]:
 # Benefit (True) or Cost (False) criteria?
I = np.array(I, dtype=np.int8)
print(I)
assert len(I.shape) == 1, "Criterion array must be 1D"
assert len(I) == n, "Criterion array wrong length, " + "should be of length {}".format(n)

[1 0 0 1]


In [199]:
# Initialise best/worst alternatives lists
ab, aw = np.zeros(n), np.zeros(n)
print(ab, aw)


[0. 0. 0. 0.] [0. 0. 0. 0.]


In [200]:
#def step1():
""" TOPSIS Step 1
Calculate the normalised decision matrix (self.r)
"""
print(a)
print(' ')
print(np.linalg.norm(a, axis=1)[:, np.newaxis])
print(' ')
r = a/np.array(np.linalg.norm(a, axis=1)[:, np.newaxis])
print(r)


[[ 90.  90.  80.  70.  60.  60.]
 [ 10.  10.  30.  30.  40.  40.]
 [100. 100. 200. 200. 200. 200.]
 [100. 100.  80.  80.  80.  80.]]
 
[[186.2793601 ]
 [ 72.11102551]
 [424.26406871]
 [213.54156504]]
 
[[0.48314531 0.48314531 0.4294625  0.37577969 0.32209688 0.32209688]
 [0.13867505 0.13867505 0.41602515 0.41602515 0.5547002  0.5547002 ]
 [0.23570226 0.23570226 0.47140452 0.47140452 0.47140452 0.47140452]
 [0.46829291 0.46829291 0.37463432 0.37463432 0.37463432 0.37463432]]


In [201]:
# def step2(self):
""" TOPSIS Step 2
Calculate the weighted normalised decision matrix
Two transposes required so that indices are multiplied correctly:
"""
print(r.T)
print(' ')
print(w)
print(' ')
v = (w * r.T).T
print(v)


[[0.48314531 0.13867505 0.23570226 0.46829291]
 [0.48314531 0.13867505 0.23570226 0.46829291]
 [0.4294625  0.41602515 0.47140452 0.37463432]
 [0.37577969 0.41602515 0.47140452 0.37463432]
 [0.32209688 0.5547002  0.47140452 0.37463432]
 [0.32209688 0.5547002  0.47140452 0.37463432]]
 
[0.25 0.25 0.25 0.25]
 
[[0.12078633 0.12078633 0.10736563 0.09394492 0.08052422 0.08052422]
 [0.03466876 0.03466876 0.10400629 0.10400629 0.13867505 0.13867505]
 [0.05892557 0.05892557 0.11785113 0.11785113 0.11785113 0.11785113]
 [0.11707323 0.11707323 0.09365858 0.09365858 0.09365858 0.09365858]]


In [202]:
#def step3(self):
""" TOPSIS Step 3
Determine the ideal and negative-ideal solutions
I[i] defines i as a member of the benefit criteria (True) or the cost
criteria (False)
"""
# Calcualte ideal/negative ideals
ab = np.max(v, axis=1) * I + np.min(v, axis=1) * (1 - I)
aw = np.max(v, axis=1) * (1 - I) + np.min(v, axis=1) * I
print(np.max(v, axis=1))
print('ab=',ab)
print('aw',aw)

[0.12078633 0.13867505 0.11785113 0.11707323]
ab= [0.12078633 0.03466876 0.05892557 0.11707323]
aw [0.08052422 0.13867505 0.11785113 0.09365858]


In [203]:
 #def step4(self):
""" TOPSIS Step 4
Calculate the separation measures, n-dimensional Euclidean distance
"""
# Create two n long arrays containing Eculidean distances
# Save the ideal and negative-ideal solutions
db = np.linalg.norm(v - ab[:,np.newaxis], axis=0)
dw = np.linalg.norm(v - aw[:,np.newaxis], axis=0)
print('db=',db)
print('dw=',dw)


db= [0.         0.         0.09491194 0.09771705 0.12829191 0.12829191]
dw= [0.12829191 0.12829191 0.043845   0.03717578 0.         0.        ]


In [227]:
# def step5(self):
""" TOPSIS Step 5 & 6
Calculate the relative closeness to the ideal solution, then rank the
preference order
"""
# Ignore division by zero errors
#np.seterr(all='ignore')
# Find relative closeness
C = dw / (dw + db)
print('C = ',C)

showArgsort = C.argsort()
print('showArgsort: ',showArgsort)

get_length = len(C)
#print(length)


#--------好的-----------
#找好的
optimum_choice = C.argsort()[-1]
count_good = 0
opt_idx = []
for i in range(get_length):
    if C[i]==C[optimum_choice]:
        #print('Name: {}(a[{}]) is : {}'.format(Name_list[i],i, a[:, i]))
        count_good+=1
        opt_idx.append(i)

if count_good==0:
    opt_idx.append(optimum_choice)


#--------不好的----------- 
#找不好的
bad_choice = C.argsort()[0]
count_bad=0
bad_idx=[]
for j in range(get_length):
    if C[j]==C[bad_choice]:
        count_bad+=1
        bad_idx.append(j)

if count_bad==0:
    bad_idx.append(bad_choice)

print('--------好的-----------')
print('Good alternative')
for idx in opt_idx:
    print('Name: {}(a[{}]) is : {}'.format(Name_list[idx],idx, a[:, idx]))

print('--------不好的-----------')
print('Bad alternative')
for idx in bad_idx:
    print('Name: {}(a[{}]) is : {}'.format(Name_list[idx],idx, a[:, idx]))


C =  [1.         1.         0.31598421 0.27559492 0.         0.        ]
showArgsort:  [4 5 3 2 0 1]
--------好的-----------
Good alternative
Name: Vendor A(a[0]) is : [ 90.  10. 100. 100.]
Name: Vendor B(a[1]) is : [ 90.  10. 100. 100.]
--------不好的-----------
Bad alternative
Name: Vendor E(a[4]) is : [ 60.  40. 200.  80.]
Name: Vendor F(a[5]) is : [ 60.  40. 200.  80.]


In [107]:
import csv

In [108]:
# 開啟 CSV 檔案
with open('../Desktop/vendorChoose.csv', newline='') as csvfile:

  # 讀取 CSV 檔案內容
  rows = csv.reader(csvfile)

  # 以迴圈輸出每一列
  for row in rows:
    print(row)

['', '品質', '交期', '價格', '服務']
['Vendor A', '90', '10', '100', '100']
['Vendor B', '90', '10', '100', '100']
['Vendor C', '80', '30', '200', '80']
['Vendor D', '70', '30', '200', '80']
['Vendor E', '60', '40', '200', '80']
['Vendor F', '60', '40', '200', '80']
